services:
  tts-api-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts-api
    environment:
      - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./speakers:/app/speakers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu
    restart: unless-stopped

  tts-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: tts-api
    environment:
      - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./speakers:/app/speakers
    profiles:
      - cpu
    restart: unless-stopped
